name: NuGet Generation

on:
  pull_request:
    types: [closed]
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          source-url: https://nuget.pkg.github.com/nexus-network-cloud/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
          
      - name: Build solution and generate NuGet package
        run: |
          cd CsharpVault/CsharpVault
          dotnet pack -c Release -o out  
      - name: Push generated package to GitHub registry
        run: |
          cd CsharVault/CsharpVault
          dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true
