name: publish to nuget
on:
  push:
    branches:
      - deploy # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build
      run: | 
        cd CsharpVault/CsharpVault
        dotnet build --configuration Release
    - name: Pack
      run: | 
        cd CsharpVault/CsharpVault
        dotnet pack CsharpVault.csproj --output nuget-packages --configuration Release
    - name: Push
      run: |
        cd CsharpVault/CsharpVault
        dotnet nuget add source --username nexus-network-cloud --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/nexus-network-cloud/index.json"
        dotnet nuget push **/*.nupkg --skip-duplicate --source https://nuget.pkg.github.com/nexus-network-cloud/index.json
